# Name of Workflow
name: First Workflow Demo

# Run this Code when pushed to Main Branch
on:
  push:
    branches: [ master ]

jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
      #step 1: check out code
      - name: Check out repository
        uses: actions/checkout@v3

      #step 2: Run a Simple Command
      - name: Print Hello
        run: echo "first workflow"

      - name: show files
        run: |
          ls -la
